### ISSUE TITLE
No module named 'make_env'

### ISSUE THREAD

**Issue by testerpce** [ermongroup/multiagent-gail#3]
On running the code  "python -m sandbox.mack.run_simple" from the terminal in a conda environment, I am getting the error, No module named 'make_env'.
The same error comes when I am running the code "python -m irl.mack.run_mack_gail [discrete]".

**Comment by jiamings** [comment]
`make_env` should appear here: https://github.com/ermongroup/multiagent-gail/tree/master/multiagent-particle-envs

I think you might want to deal with python path, or use `pip install -e .` in the particle env directory.
